apiVersion: apps/v1
kind: Deployment
metadata:
  name: personality-api-deployment
  labels:
    app: personality-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personality-api
  template:
    metadata:
      labels:
        app: personality-api
    spec:
      containers:
      - name: api
        image: 740820043343.dkr.ecr.us-east-1.amazonaws.com/personality-prediction-api:4986a65ea6f8ce63346367571b6d9d217636b591
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: aws-registry-key